events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {

    listen 5000;

    location / {
      root /usr/share/nginx/html;
      index index.html;
    }

    location /auth/ {
      proxy_pass http://auth-service:8080/;
    }

    location /orders/ {
      proxy_pass http://order-service:8081/;
    }

    location /products/ {
      proxy_pass http://product-service:8082/;
    }

    location /payments/ {
      proxy_pass http://payment-service:8083/;
    }

    location /notifications/ {
      proxy_pass http://notification-service:8084/;
    }

    location /profiles/ {
      proxy_pass http://profile-service:8085/;
    }
  }
}