version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./terraform/frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./terraform/frontend/html:/usr/share/nginx/html
    depends_on:
      - auth-service
      - order-service
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=app
      - DB_MODE=disable
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - app-network

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=app
      - DB_MODE=disable
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d app"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./terraform/db_init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./terraform/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - auth-service
      - order-service
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: