apiVersion: v1
kind: Secret

metadata:
  name: app-secret

type: Opaque

stringData:
  DB_USER: "admin"
  DB_PASSWORD: "admin"

  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"

  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"